sftp:
#Host in the form of hostname or ip address
  host: Host here
#User that will connect to server
  user: User Here
#Password that is tied to user
  password: Password Here
#abspath is where we will store the files once we connect to the server.
  abspath: /home/some_user/pytamate/automate/uncommitted/
#localpath is where the files are stored locally, only use relative path
  localpath: local/
#location assigned based on ip address
  location:
    127.0.0.1: OFFLINE
    172.16.30.1: Office 1
    10.0.10.1: Office 2
    192.168.1.1: Office 3
